source "https://rubygems.org"

gem "nokogiri", "= 1.6.8.1"
gem "berkshelf"
gem "chefspec"
gem "serverspec"
gem "foodcritic"
gem "rubocop"
gem "pry-byebug"
gem "test-kitchen"
gem "kitchen-docker"
gem "rspec_junit_formatter"
